PLAT_TYPE_APP   = 1 #APP
PLAT_TYPE_WEB   = 2 #网站


ROLE_TYPE_NONE  = 0 #无身份
ROLE_TYPE_TRSP  = 1 #司机
ROLE_TYPE_CSGN  = 2 #货主
ROLE_TYPE_CONV  = 3 #车队


CARGO_TYPE_STANDARD   = 1   #货物类型:标准
CARGO_TYPE_NOSTANDARD = 2   #货物类型:非标准
CARGO_TYPE_ALL = [CARGO_TYPE_STANDARD, CARGO_TYPE_NOSTANDARD]


RENT_TYPE_AMOUNT   = 1  #用车类型:按重量体积
RENT_TYPE_TOTAL    = 2  #用车类型:包车
RENT_TYPE_ALL = [RENT_TYPE_AMOUNT, RENT_TYPE_TOTAL]


INDENT_STATUS_PUBLISHING    = 1 #发布中
INDENT_STATUS_GOTOSTART     = 2 #前往装货点
INDENT_STATUS_LOADING       = 3 #装货中
INDENT_STATUS_LOADCONFIRM   = 4 #货主确认装货完成中
INDENT_STATUS_TRANSPORTING  = 5 #运货中
INDENT_STATUS_UNLOADING     = 6 #御货中
INDENT_STATUS_UNLOADCONFIRM = 7 #货主确认御货完成中
INDENT_STATUS_COMPLETE      = 8 #完成
