CARGO_TYPE_STANDARD     = 1
CARGO_TYPE_NOSTANDARD = 2
CARGO_TYPE_ALL = [CARGO_TYPE_STANDARD, CARGO_TYPE_NOSTANDARD]


RENT_TYPE_TIME     = 1
RENT_TYPE_TOTAL    = 2
RENT_TYPE_ALL = [RENT_TYPE_TIME, RENT_TYPE_TOTAL]
