CARGO_TYPE_STANDARD     = 1
CARGO_TYPE_NOSTANDARD = 2
CARGO_TYPE_ALL = [CARGO_TYPE_STANDARD, CARGO_TYPE_NOSTANDARD]


RENT_TYPE_TIME     = 1
RENT_TYPE_TOTAL    = 2
RENT_TYPE_ALL = [RENT_TYPE_TIME, RENT_TYPE_TOTAL]


INDENT_STATUS_PUBLISHING = 1
INDENT_STATUS_GOTOSTART = 2
INDENT_STATUS_PHOTO1 = 2
INDENT_STATUS_LOADCARGO = 2
INDENT_STATUS_LOADCONF = 2
INDENT_STATUS_TRANSPORT = 2

INDENT_STATUS_LOADCARGO = 2
INDENT_STATUS_LOADCARGO = 2
INDENT_STATUS_LOADCARGO = 2
INDENT_STATUS_LOADCARGO = 2
